name: Start self-hosted runner and execute jobs
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  startfargate:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
    
      - name: start Fargate
        run: aws ecs run-task --cluster cluster --task-definition task:4 --count 1 --network-configuration "awsvpcConfiguration={subnets=[subnet-087e20ba48b8b9722],securityGroups=[sg-02a9e9ed68fca1110],assignPublicIp=ENABLED}" --launch-type FARGATE --override '{"containerOverrides":[{"name":"Github-Runner","environment":[{"name":"RUNNER_LABELS","value":"${{github.sha}}"}]}]}'


  run-self-hosted:
    name: exexcute the code
    needs: startfargate
    runs-on: [self-hosted, "${{github.sha}}" ]
    steps:
   
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: sleep
        run: sleep 120 
        
# Please add your steps here   
        

